# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3740c2ac635f78bb1477888f987040f6659e9c206309165e2b3ee77bff63ca3aee3622dc0b920a32e3605c5905a114b2dfabed406a71087dfa4ac45bef8da9bb

test:
  secret_key_base: 9548afcd2ea868b200f05889b3d7b42f1fae65a6bd2d3a13c8c1b3b97d3c29805a459b40ce7ba1fcd09a46a070f355d9b6cd641b98523b56387626e24d591ee1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
